//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProductwebServise.ProductWebServiceReferenceComsumer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunSonuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UrunSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UrunIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        private System.Nullable<decimal> FiyatField;
        
        private System.Nullable<short> StokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UrunId {
            get {
                return this.UrunIdField;
            }
            set {
                if ((this.UrunIdField.Equals(value) != true)) {
                    this.UrunIdField = value;
                    this.RaisePropertyChanged("UrunId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<short> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductWebServiceReferenceComsumer.ProductWebServiceSoap")]
    public interface ProductWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponse HelloWorld(ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponse> HelloWorldAsync(ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name UrunleriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunleriGetir", ReplyAction="*")]
        ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponse UrunleriGetir(ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunleriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponse> UrunleriGetirAsync(ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunleriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunleriGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequestBody Body;
        
        public UrunleriGetirRequest() {
        }
        
        public UrunleriGetirRequest(ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UrunleriGetirRequestBody {
        
        public UrunleriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunleriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunleriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponseBody Body;
        
        public UrunleriGetirResponse() {
        }
        
        public UrunleriGetirResponse(ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrunleriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunSonuc> UrunleriGetirResult;
        
        public UrunleriGetirResponseBody() {
        }
        
        public UrunleriGetirResponseBody(System.Collections.Generic.List<ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunSonuc> UrunleriGetirResult) {
            this.UrunleriGetirResult = UrunleriGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWebServiceSoapChannel : ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWebServiceSoapClient : System.ServiceModel.ClientBase<ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap>, ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap {
        
        public ProductWebServiceSoapClient() {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponse ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap.HelloWorld(ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest inValue = new ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest();
            inValue.Body = new ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequestBody();
            ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponse retVal = ((ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponse> ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap.HelloWorldAsync(ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldResponse> HelloWorldAsync() {
            ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest inValue = new ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequest();
            inValue.Body = new ClientProductwebServise.ProductWebServiceReferenceComsumer.HelloWorldRequestBody();
            return ((ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponse ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap.UrunleriGetir(ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest request) {
            return base.Channel.UrunleriGetir(request);
        }
        
        public System.Collections.Generic.List<ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunSonuc> UrunleriGetir() {
            ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest inValue = new ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest();
            inValue.Body = new ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequestBody();
            ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponse retVal = ((ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap)(this)).UrunleriGetir(inValue);
            return retVal.Body.UrunleriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponse> ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap.UrunleriGetirAsync(ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest request) {
            return base.Channel.UrunleriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirResponse> UrunleriGetirAsync() {
            ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest inValue = new ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequest();
            inValue.Body = new ClientProductwebServise.ProductWebServiceReferenceComsumer.UrunleriGetirRequestBody();
            return ((ClientProductwebServise.ProductWebServiceReferenceComsumer.ProductWebServiceSoap)(this)).UrunleriGetirAsync(inValue);
        }
    }
}
