//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProductwebServise.MusteriWebServiceReferenceConsumer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusteriSonuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MusteriSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MusteriId {
            get {
                return this.MusteriIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriIdField, value) != true)) {
                    this.MusteriIdField = value;
                    this.RaisePropertyChanged("MusteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SirketAdi {
            get {
                return this.SirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdiField, value) != true)) {
                    this.SirketAdiField = value;
                    this.RaisePropertyChanged("SirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MusteriAdi {
            get {
                return this.MusteriAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriAdiField, value) != true)) {
                    this.MusteriAdiField = value;
                    this.RaisePropertyChanged("MusteriAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name MusteriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGetir", ReplyAction="*")]
        ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponse MusteriGetir(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponse> MusteriGetirAsync(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequestBody Body;
        
        public MusteriGetirRequest() {
        }
        
        public MusteriGetirRequest(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MusteriGetirRequestBody {
        
        public MusteriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponseBody Body;
        
        public MusteriGetirResponse() {
        }
        
        public MusteriGetirResponse(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriSonuc[] MusteriGetirResult;
        
        public MusteriGetirResponseBody() {
        }
        
        public MusteriGetirResponseBody(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriSonuc[] MusteriGetirResult) {
            this.MusteriGetirResult = MusteriGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap>, ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponse ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap.MusteriGetir(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest request) {
            return base.Channel.MusteriGetir(request);
        }
        
        public ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriSonuc[] MusteriGetir() {
            ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest inValue = new ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest();
            inValue.Body = new ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequestBody();
            ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponse retVal = ((ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap)(this)).MusteriGetir(inValue);
            return retVal.Body.MusteriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponse> ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap.MusteriGetirAsync(ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest request) {
            return base.Channel.MusteriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirResponse> MusteriGetirAsync() {
            ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest inValue = new ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequest();
            inValue.Body = new ClientProductwebServise.MusteriWebServiceReferenceConsumer.MusteriGetirRequestBody();
            return ((ClientProductwebServise.MusteriWebServiceReferenceConsumer.CustomerWebServiceSoap)(this)).MusteriGetirAsync(inValue);
        }
    }
}
